import ctypes
from ctypes import *

def VAR_COUNT(x):
	a = (x).var_data_count_h << 8
	b = (x).var_data_count_l
	return (a|b)
	
def SET_VAR_COUNT(dts, n):
	(dts).var_data_count_h = (n) >> 8
	(dts).var_data_count_l = (n) & 0xFF
	
class DTS_pointer(Union):
	_fields_ = [("byte_data", POINTER(c_ubyte)),
				("word_data", POINTER(c_ushort)),
				("dword_data", POINTER(c_uint)),
				("float_data", POINTER(c_float))]

TS_CFGITEMHEADER_CONSTANT_INPUT = 0xFFF0

ENGINELAB_MODIFY_DLL_VERSION  = 96

class GenericArray_DTS(Structure):
	_fields_ = [("var_data_size"   , c_ubyte),
				("var_data_count_h", c_ubyte),
				("var_data_count_l", c_ubyte),
				("var"             , DTS_pointer)]

# PositionSensor_TS.edge_trigger
TS_POSITIONSENSOR_EDGE_TRIGGER_RISINGEDGE  = 0
TS_POSITIONSENSOR_EDGE_TRIGGER_FALLINGEDGE  = 1
TS_POSITIONSENSOR_EDGE_TRIGGER_RISINGFALLINGEDGES  = 2
TS_POSITIONSENSOR_EDGE_TRIGGER_COUNT_  = 3
class PositionSensor_TS(Structure):
	_fields_ = [("harness_pin_number",  c_ubyte),
				("noise_cancellation",  c_ubyte),
				("number_of_teeth",  c_ubyte),
				("edge_trigger",  c_ubyte)]

# ConfigurationItemHeader_modifiable_TS.mod_flags
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_PRIVATE_ITEM_SHIFT  = 11
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_PRIVATE_ITEM_MASK  = 0x0800
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_PRIVATE_ITEM_ON  = 0x0800
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_HIDDEN_SHIFT  = 0
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_HIDDEN_MASK  = 0x0001
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_HIDDEN_ON  = 0x0001
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_CLAMP_OUTPUT_SHIFT  = 12
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_CLAMP_OUTPUT_MASK  = 0x1000
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_CLAMP_OUTPUT_ON  = 0x1000
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_USE_TEST_OUTPUT_SHIFT  = 13
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_USE_TEST_OUTPUT_MASK  = 0x2000
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_USE_TEST_OUTPUT__  = 0x2000
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_PASSWORD_PROTECT_SHIFT  = 14
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_PASSWORD_PROTECT_MASK  = 0x4000
TS_CFGITEMHEADER_MODIFIABLE_MOD_FLAGS_PASSWORD_PROTECT__  = 0x4000
class ConfigurationItemHeader_modifiable_TS(Structure):
	_fields_ = [("outputValue",  c_float),
				("outputValueInitial",  c_float),
				("outputValueTest",  c_float),
				("clamp_lower",  c_float),
				("clamp_upper",  c_float),
				("type",  c_ubyte),
				("outputChannel",  c_ushort),
				("channel_name",  GenericArray_DTS),
				("input_channels",  GenericArray_DTS),
				("input_data_pointers",  GenericArray_DTS),
				("mod_flags",  c_ushort)]

# ConfigurationEngineDescriptorItem_modifiable_TS.cycles
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_CYCLES_TWOSTROKE  = 2
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_CYCLES_FOURSTROKE  = 4
# ConfigurationEngineDescriptorItem_modifiable_TS.timing_type
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_SINGLETOOTHCAM  = 0
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_HONDA600RR  = 1
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_SINGLECAMCRANK1TOOTHMISSING  = 2
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_SINGLECAMCRANK1TOOTHMISSING_VVT  = 3
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_SINGLECAMCRANK2TOOTHMISSING  = 4
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_SINGLECAMCRANK2TOOTHMISSING_VVT  = 5
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_HONDACIVIC_5T_CAM_12_1CRANK  = 6
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_HONDARSX_5T_4T_CAMS_12_1CRANK_VVT  = 7
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_SUBARUWRXSTI_3T_3T_2T_2T_CAMS_36_2_2_2CRANK_VVT  = 8
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_1GDSM_2T_CAM_4_CRANK  = 9
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_NISSAN_QG18DE_10T_CAM_36_2_CRANK  = 10
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_DODGENGC_15T_CAM_36_2_2_CRANK_VVT  = 11
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_DODGEVIPER92_95_4T_CAM_20_2_2_2_2_2_CRANK  = 12
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_DODGEVIPER96_1T_CAM_20_2_2_2_2_2_CRANK  = 13
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_MITSUBISHIEVO8_9_2T_CAM_4_CRANK_VVT  = 14
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_GM_LS7_4T_CAM_60_2_CRANK_VVT  = 15
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_BMW_S54_7T_6T_CAMS_60_2_CRANK_VVT  = 16
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_BMW_S65_7T_6T_CAMS_60_2_CRANK_VVT  = 17
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_NISSAN_VQ35_6T_6T_CAMS_36_2_2_2_CRANK_VVT  = 18
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_NISSAN_VQ35_6T_6T_3T_3T_CAMS_36_2_2_2_CRANK_VVT  = 19
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_NISSAN_VQ37_6T_6T_CAMS_36_2_2_2_CRANK_VVT  = 20
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_TOYOTA_2JZGTE_3T_CAM_36_2_CRANK_VVT  = 21
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_DODGEVIPER4THGENERATION_5T_CAM_60_2_CRANK  = 22
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_HONDAJ35_37_3T_CAM_24_1_1_CRANK  = 23
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_SUBARUEZ36_3T_3T_3T_3T_CAMS_36_2_2_2CRANK_VVT  = 24
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_HONDAF22C_3T_CAM_12_CRANK_VVT  = 25
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_PORSCHE997_4T_4T_CAMS_60_2_CRANK_VVT  = 26
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_FORDCOYOTE_7T_7T_7T_7T_CAMS_36_1_CRANK_VVT  = 27
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_VOLKSWAGON_4T_CAMS_60_2_CRANK_VVT  = 28
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_LAMBORGHINI_4T_4T_4T_4T_CAMS_36_1_1_1_1_CRANK_VVT  = 29
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_GM_LFX_4T_4T_4T_4T_CAMS_60_2_CRANK_VVT  = 30
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_TOYOTA_2GR_FE_3T_3T_3T_3T_CAMS_36_2_CRANK_VVT  = 31
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_YAMAHA_1800_1_CAM_4_1_CRANK  = 32
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_NISSAN_RB26DETT_6_CAM_180_CRANK  = 33
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_NISSAN_SR20DET_4_CAM_180_CRANK  = 34
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_FORD_4_6_3V_5_5_CAM_36_1_CRANK  = 35
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_MAZDA_L_MZR_6_CAM_36_2_2_2_CRANK_VVT  = 36
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_TOYOTA_3SGE_3T_CAM_36_2_CRANK_VVT  = 37
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_TIMING_TYPE_COUNT_  = 38
# ConfigurationEngineDescriptorItem_modifiable_TS.sync_response
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_NOT_SYNCED  = 0
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNCED  = 1
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_CRANK_TOOTH_MISSED  = 2
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_CRANK_TOOTH_PRESENT  = 3
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_PRIMARY_CAM_SIGNATURE  = 4
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY_CAM_SIGNATURE  = 5
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY0_CAM_SIGNATURE  = 6
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY1_CAM_SIGNATURE  = 7
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY2_CAM_SIGNATURE  = 8
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY3_CAM_SIGNATURE  = 9
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY4_CAM_SIGNATURE  = 10
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY5_CAM_SIGNATURE  = 11
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY6_CAM_SIGNATURE  = 12
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY7_CAM_SIGNATURE  = 13
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY8_CAM_SIGNATURE  = 14
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY9_CAM_SIGNATURE  = 15
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY10_CAM_SIGNATURE  = 16
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY11_CAM_SIGNATURE  = 17
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY12_CAM_SIGNATURE  = 18
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY13_CAM_SIGNATURE  = 19
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY14_CAM_SIGNATURE  = 20
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_SECONDARY15_CAM_SIGNATURE  = 21
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC0  = 22
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC1  = 23
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC2  = 24
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC3  = 25
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC4  = 26
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC5  = 27
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC6  = 28
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC7  = 29
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC8  = 30
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_STATE_SYNC_ERROR_GENERIC9  = 31
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_SYNC_RESPONSE_COUNT_  = 32
# ConfigurationEngineDescriptorItem_modifiable_TS.coil_type
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_SETUP_SHIFT  = 0
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_SETUP_MASK  = 0x03
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_SETUP_COP  = 0x00
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_SETUP_WASTED_SPARK  = 0x01
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_SETUP_DISTRIBUTOR  = 0x02
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_INVERT_SHIFT  = 2
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_INVERT_MASK  = 0x04
TS_ENGINEDESCRIPTOR_ITEM_MODIFIABLE_COIL_TYPE_INVERT__  = 0x04
class ConfigurationEngineDescriptorItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("crank",  PositionSensor_TS),
				("cam0",  PositionSensor_TS),
				("cam1",  PositionSensor_TS),
				("cam2",  PositionSensor_TS),
				("cam3",  PositionSensor_TS),
				("noise_cancellation_mode",  c_ubyte),
				("num_coils",  c_ubyte),
				("num_sparks",  c_ubyte),
				("num_injectors",  c_ubyte),
				("coil_type",  c_ubyte),
				("num_cylinders",  c_ubyte),
				("cycles",  c_ubyte),
				("timing_type",  c_ubyte),
				("displacement",  c_float),
				("spark_base_timings",  GenericArray_DTS),
				("injector_base_timings",  GenericArray_DTS),
				("spark_knock_sense_indexes",  GenericArray_DTS),
				("spark_knock_sense_timings",  GenericArray_DTS),
				("spark_knock_sense_widths",  GenericArray_DTS),
				("sync_response",  GenericArray_DTS),
				("misc_settings",  GenericArray_DTS),
				("crank_speed_sparking_toothoffset",  c_ubyte),
				("crank_speed_sparking_toothcount",  c_ubyte),
				("gdi_pump_cam_number",  c_ubyte),
				("gdi_pump_cam_number_of_lobes",  c_ubyte)]

class ConfigurationPassthroughItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationAnalogInputConditioningItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("input_min",  c_float),
				("input_max",  c_float),
				("clamping_override",  c_float),
				("clamping_override_enable",  c_ubyte)]

class ConfigurationPredefItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationMathItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationIfElseItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

# Configuration1DTableItem_modifiable_DTS.cell_adjust
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_DISABLED  = 0
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_ASSIGN  = 1
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_ADD  = 2
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_MULTIPLY  = 3
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_50  = 10
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_60  = 20
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_70  = 30
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_80  = 40
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_90  = 50
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_91  = 60
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_92  = 70
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_93  = 80
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_94  = 90
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_95  = 100
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_96  = 120
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_97  = 140
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_98  = 160
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_99  = 180
TS_1DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_100  = 200
class Configuration1DTableItem_modifiable_DTS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("axis_points",  GenericArray_DTS),
				("range_min",  c_float),
				("range_max",  c_float),
				("interpolate",  c_ubyte),
				("axis_selector",  c_ubyte),
				("cell_adjust",  c_ubyte),
				("var_data_size"   , c_ubyte),
				("var_data_count_h", c_ubyte),
				("var_data_count_l", c_ubyte),
				("var"             , DTS_pointer)]

# Configuration2DTableItem_modifiable_DTS.cell_adjust
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_DISABLED  = 0
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_ASSIGN  = 1
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_ADD  = 2
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_MULTIPLY  = 3
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_50  = 10
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_60  = 20
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_70  = 30
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_80  = 40
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_90  = 50
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_91  = 60
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_92  = 70
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_93  = 80
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_94  = 90
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_95  = 100
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_96  = 120
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_97  = 140
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_98  = 160
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_99  = 180
TS_2DTABLE_ITEM_MODIFIABLE_CELL_ADJUST_FILTER_100  = 200
class Configuration2DTableItem_modifiable_DTS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("axis0_points",  GenericArray_DTS),
				("axis1_points",  GenericArray_DTS),
				("range_min",  c_float),
				("range_max",  c_float),
				("interpolate",  c_ubyte),
				("axis0_selector",  c_ubyte),
				("axis1_selector",  c_ubyte),
				("cell_adjust",  c_ubyte),
				("var_data_size"   , c_ubyte),
				("var_data_count_h", c_ubyte),
				("var_data_count_l", c_ubyte),
				("var"             , DTS_pointer)]

class ConfigurationRunningAverageItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationSlopeItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationMultiplexItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationMafFuelRequirementItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationLimitingItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationProfilerItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationEmbeddedCodeItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("storage",  GenericArray_DTS),
				("locals",  GenericArray_DTS)]

class ConfigurationUnitConversionItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

# ConfigurationThermistorItem_modifiable_TS._output_type
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_RESISTANCEOHMS  = 0
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_COOLANTTEMPDEGC  = 1
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_AIRTEMPDEGC  = 2
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_1GDSM_DEGC  = 3
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_GM12146312_DEGC  = 4
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_SUPRA_19937_DEGC  = 5
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_HONDA1990_01_DEGC  = 6
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_HONDA2002_06_DEGC  = 7
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_SUBARU2004_06_DEGC  = 8
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_EVO89_2GDSM_DEGC  = 9
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_CLT_ACURACLT_DEGC  = 10
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_AIR_GM25036751_DEGC  = 11
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_AIR_HONDAS2000_00_05_DEGC  = 12
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_AIR_HONDA1990_01_DEGC  = 13
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_AIR_SUBARUSTI2004_06_DEGC  = 14
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_AIR_TOYOTAMAF_DEGC  = 15
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_AIR_NISSAN_DEGC  = 16
TS_THERMISTOR_ITEM_MODIFIABLE__OUTPUT_TYPE_COUNT_  = 17
class ConfigurationThermistorItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("_output_type",  c_ubyte)]

class ConfigurationPIDItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationObdiiPIDItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationObdiiTIDItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationSpeedDensityItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationTimerItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

# ConfigurationHardwareIOItem_modifiable_TS.harness_pin_mode
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_PULLUP_4700_OHM  = 0
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_PULLUP_10000_OHM  = 1
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_PULLUP_2200_OHM  = 2
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_2_AMP  = 3
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_5_AMP  = 4
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_10_AMP  = 5
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_HIGHSIDE_2_AMP  = 6
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_HIGHSIDE_5_AMP  = 7
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_HIGHSIDE_10_AMP  = 8
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_VARIABLE_RELUCTANCE  = 9
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_OPEN_COLLECTOR_200_MAMP  = 10
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_OPEN_COLLECTOR_4_AMP  = 11
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_NO_DRIVE_DIRECT_CONNECT  = 12
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_2_8_AMP  = 13
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_2_8_WPULLUP  = 14
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_6_AMP  = 15
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_6_WPULLUP  = 16
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_18_AMP  = 17
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_18_WPULLUP  = 18
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_INPUT_TRANSISTOR_SWITCH  = 19
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_INPUT_TRANSISTOR_WPULLUP  = 20
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_OPTOCOUPLER  = 21
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_STEPPERMOTORCONTROLLER  = 22
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_2_8_WFLYBACK  = 23
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_6_WFLYBACK  = 24
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_LOWSIDE_18_WFLYBACK  = 25
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_RS232_RX  = 26
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_RS232_TX  = 27
TS_HARDWAREIO_ITEM_MODIFIABLE_HARNESS_PIN_MODE_COUNT_  = 28
class ConfigurationHardwareIOItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("harness_pin_mode",  c_ubyte)]

# ConfigurationFixed1DTableItem_modifiable_TS._table_type
TS_FIXED1DTABLE_ITEM_MODIFIABLE__TABLE_TYPE_MASSAIRFLOWSENSORLS1  = 0
TS_FIXED1DTABLE_ITEM_MODIFIABLE__TABLE_TYPE_MASSAIRFLOWSENSORLS6  = 1
TS_FIXED1DTABLE_ITEM_MODIFIABLE__TABLE_TYPE_COUNT_  = 2
class ConfigurationFixed1DTableItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("_table_type",  c_ushort)]

class ConfigurationPlantHardwareWriterItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationDiagnosticCodeItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationLatchItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationLambdaStagedItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("primary_fuel_stoich_af",  c_float),
				("primary_fuel_density",  c_float),
				("secondary_fuel_stoich_af",  c_float),
				("secondary_fuel_density",  c_float),
				("number_of_primary_injectors",  c_ubyte),
				("number_of_secondary_injectors",  c_ubyte),
				("primary_injector_numbers",  GenericArray_DTS),
				("secondary_injector_numbers",  GenericArray_DTS)]

class ConfigurationPrivateItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationCAN_SimpleTransmitItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("CAN_channel",  c_ubyte),
				("CAN_id",  c_ulong),
				("data_buffer",  GenericArray_DTS)]

# ConfigurationCJ125Item_modifiable_TS.read_latch
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_EDGE_SHIFT  = 0
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_EDGE_MASK  = 0x03
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_EDGE_RISING_EDGE  = 0x01
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_EDGE_FALLING_EDGE  = 0x02
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_START_STATE_SHIFT  = 4
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_START_STATE_MASK  = 0x30
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_START_STATE_ZERO  = 0x00
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_START_STATE_NON_ZERO  = 0x10
TS_CJ125_ITEM_MODIFIABLE_READ_LATCH_START_STATE_COUNT_  = 2
# ConfigurationCJ125Item_modifiable_TS.write_latch
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_SHIFT  = 0
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_MASK  = 0x03
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_RISING_EDGE  = 0x01
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_FALLING_EDGE  = 0x02
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_SHIFT  = 4
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_MASK  = 0x30
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_ZERO  = 0x00
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_NON_ZERO  = 0x10
TS_CJ125_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_COUNT_  = 2
class ConfigurationCJ125Item_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("read_latch",  c_ubyte),
				("write_latch",  c_ubyte)]

# ConfigurationEALEventItem_modifiable_TS.event_latch
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_SHIFT  = 0
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_MASK  = 0x03
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_RISING_EDGE  = 0x01
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_FALLING_EDGE  = 0x02
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_SHIFT  = 4
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_MASK  = 0x30
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_ZERO  = 0x00
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_NON_ZERO  = 0x10
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_COUNT_  = 2
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED_SHIFT  = 6
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED_MASK  = 0x40
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED__  = 0x40
# ConfigurationEALEventItem_modifiable_TS.event_type
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_INJECTOR_EVENT_SHIFT  = 0
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_INJECTOR_EVENT_MASK  = 0x01
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_INJECTOR_EVENT__  = 0x01
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_SPARK_EVENT_SHIFT  = 1
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_SPARK_EVENT_MASK  = 0x02
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_SPARK_EVENT__  = 0x02
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_SAVE_DATA_AND_COMMIT_EVENT_SHIFT  = 2
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_SAVE_DATA_AND_COMMIT_EVENT_MASK  = 0x04
TS_EALEVENT_ITEM_MODIFIABLE_EVENT_TYPE_SAVE_DATA_AND_COMMIT_EVENT__  = 0x04
class ConfigurationEALEventItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("event_latch",  c_ubyte),
				("event_type",  c_ubyte),
				("event_index",  c_ubyte),
				("save_data",  GenericArray_DTS)]

# ConfigurationHIP9011Item_modifiable_TS.write_latch
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_SHIFT  = 0
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_MASK  = 0x03
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_RISING_EDGE  = 0x01
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_EDGE_FALLING_EDGE  = 0x02
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_SHIFT  = 4
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_MASK  = 0x30
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_ZERO  = 0x00
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_NON_ZERO  = 0x10
TS_HIP9011_ITEM_MODIFIABLE_WRITE_LATCH_START_STATE_COUNT_  = 2
class ConfigurationHIP9011Item_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("write_latch",  c_ubyte),
				("bandpassfilterfrequency",  c_ubyte),
				("gaincontrol",  c_ubyte),
				("integratortimeconstant",  c_ubyte),
				("test",  c_ubyte),
				("prescalar",  c_ubyte)]

class ConfigurationPlaybackItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

# ConfigurationCommunicationSimpleItem_modifiable_TS.data_type
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT8  = 0
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT16  = 1
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT32  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_FLOAT  = 3
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT8  = 4
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT16  = 5
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT32  = 6
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_FLOAT  = 7
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT8  = 8
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT16  = 9
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT32  = 10
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_FLOAT  = 11
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT16_2_INT32  = 12
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT16_2_FLOAT  = 13
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT16_2_INT32  = 14
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT16_2_FLOAT  = 15
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT8_2_INT32  = 16
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_UINT8_2_FLOAT  = 17
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT8_2_INT32  = 18
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_INT8_2_FLOAT  = 19
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_DATA_TYPE_COUNT_  = 20
# ConfigurationCommunicationSimpleItem_modifiable_TS.channel_bus_override
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_TYPE_SHIFT  = 0
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_TYPE_MASK  = 0x01
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_TYPE_CAN  = 0x00
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_TYPE_SERIAL  = 0x01
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_TYPE_COUNT_  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_SHIFT  = 1
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_MASK  = 0x02
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_CHANNELA  = 0x00
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_CHANNELB  = 0x02
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_COUNT_  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_SHIFT  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_MASK  = 0x04
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_TRANSMIT  = 0x00
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_RECEIVE  = 0x04
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_COUNT_  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_TYPE_SHIFT  = 3
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_TYPE_MASK  = 0x08
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_TYPE_STANDARD_FORMAT  = 0x00
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_TYPE_EXTENDED_FORMAT  = 0x08
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_TYPE_COUNT_  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_8BYTE_PER_CONTIGUOUS_ADDRESS_SHIFT  = 4
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_8BYTE_PER_CONTIGUOUS_ADDRESS_MASK  = 0x10
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_CAN_8BYTE_PER_CONTIGUOUS_ADDRESS__  = 0x10
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_INPUT_OVERRIDE_SHIFT  = 5
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_INPUT_OVERRIDE_MASK  = 0x20
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_INPUT_OVERRIDE__  = 0x20
# ConfigurationCommunicationSimpleItem_modifiable_TS.id_dataformat
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_DATA_BITS_SHIFT  = 0
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_DATA_BITS_MASK  = 0x00000003
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_DATA_BITS_BITS7  = 0x00000000
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_DATA_BITS_BITS8  = 0x00000001
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_DATA_BITS_COUNT_  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PARITY_SHIFT  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PARITY_MASK  = 0x0000000C
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PARITY_PARITY_NONE  = 0x00000000
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PARITY_PARITY_EVEN  = 0x00000004
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PARITY_PARITY_ODD  = 0x00000008
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PARITY_COUNT_  = 3
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_STOP_BITS_SHIFT  = 4
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_STOP_BITS_MASK  = 0x00000010
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_STOP_BITS_STOPBITS1  = 0x00000000
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_STOP_BITS_STOPBITS2  = 0x00000010
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_STOP_BITS_COUNT_  = 2
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PCLK_DIV_SHIFT  = 5
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PCLK_DIV_MASK  = 0x00000060
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PCLK_DIV_PCLK_DIV_1  = 0x00000000
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PCLK_DIV_PCLK_DIV_4  = 0x00000020
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PCLK_DIV_PCLK_DIV_16  = 0x00000040
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PCLK_DIV_PCLK_DIV_64  = 0x00000060
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_PCLK_DIV_COUNT_  = 4
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_BAUDRATEGEN_N_SHIFT  = 8
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_BAUDRATEGEN_N_MASK  = 0x0000FF00
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_CAN_ID_SHIFT  = 0
TS_COMMUNICATIONSIMPLE_ITEM_MODIFIABLE_ID_DATAFORMAT_CAN_ID_MASK  = 0xFFFFFFFF
class ConfigurationCommunicationSimpleItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("channel_bus_override",  c_ubyte),
				("id_dataformat",  c_ulong),
				("input_overrides",  GenericArray_DTS),
				("data_type",  GenericArray_DTS),
				("data_min_value",  GenericArray_DTS),
				("data_max_value",  GenericArray_DTS),
				("data_buffer",  GenericArray_DTS)]

class ConfigurationModelIDItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("str0",  GenericArray_DTS),
				("str1",  GenericArray_DTS),
				("str2",  GenericArray_DTS),
				("str3",  GenericArray_DTS)]

# ConfigurationCANPacketItem_modifiable_TS.data_type
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT8  = 0
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT16  = 1
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT32  = 2
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_FLOAT  = 3
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT8  = 4
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT16  = 5
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT32  = 6
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_FLOAT  = 7
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT8  = 8
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT16  = 9
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT32  = 10
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_FLOAT  = 11
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT16_2_INT32  = 12
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT16_2_FLOAT  = 13
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT16_2_INT32  = 14
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT16_2_FLOAT  = 15
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT8_2_INT32  = 16
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_UINT8_2_FLOAT  = 17
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT8_2_INT32  = 18
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_INT8_2_FLOAT  = 19
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_UINT8  = 20
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_UINT16  = 21
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_UINT32  = 22
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_SIGNMAG8  = 23
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_SIGNMAG16  = 24
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_SIGNMAG32  = 25
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_SIGNMAG8_2_FLOAT  = 26
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_SIGNMAG16_2_FLOAT  = 27
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_SIGNMAG32_2_FLOAT  = 28
TS_CANPACKET_ITEM_MODIFIABLE_DATA_TYPE_COUNT_  = 29
# ConfigurationCANPacketItem_modifiable_TS.channel_bus_override
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_SHIFT  = 1
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_MASK  = 0x02
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_CHANNELA  = 0x00
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_CHANNELB  = 0x02
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_COUNT_  = 2
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_SHIFT  = 2
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_MASK  = 0x04
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_TRANSMIT  = 0x00
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_RECEIVE  = 0x04
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_COUNT_  = 2
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_SHIFT  = 3
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_MASK  = 0x08
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_PERIODIC  = 0x00
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_EVENT  = 0x08
TS_CANPACKET_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_COUNT_  = 2
# ConfigurationCANPacketItem_modifiable_TS.event_latch
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_SHIFT  = 0
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_MASK  = 0x03
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_RISING_EDGE  = 0x01
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_FALLING_EDGE  = 0x02
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_SHIFT  = 4
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_MASK  = 0x30
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_ZERO  = 0x00
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_NON_ZERO  = 0x10
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_COUNT_  = 2
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED_SHIFT  = 6
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED_MASK  = 0x40
TS_CANPACKET_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED__  = 0x40
class ConfigurationCANPacketItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("addresses",  GenericArray_DTS),
				("data_min_value",  GenericArray_DTS),
				("data_max_value",  GenericArray_DTS),
				("internal_input_data_pointers",  GenericArray_DTS),
				("internal_inputs",  GenericArray_DTS),
				("suggested_iteration_count",  GenericArray_DTS),
				("data_shift",  GenericArray_DTS),
				("data_bits",  GenericArray_DTS),
				("data_type",  GenericArray_DTS),
				("channel_bus_override",  c_ubyte),
				("event_latch",  c_ubyte)]

# ConfigurationSerialStreamItem_modifiable_TS.data_type
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT8  = 0
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT16  = 1
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_INT32  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_FLOAT  = 3
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT8  = 4
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT16  = 5
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_INT32  = 6
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT32_2_FLOAT  = 7
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT8  = 8
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT16  = 9
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_INT32  = 10
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT32_2_FLOAT  = 11
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT16_2_INT32  = 12
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT16_2_FLOAT  = 13
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT16_2_INT32  = 14
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT16_2_FLOAT  = 15
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT8_2_INT32  = 16
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_UINT8_2_FLOAT  = 17
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT8_2_INT32  = 18
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_INT8_2_FLOAT  = 19
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_UINT8  = 20
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_UINT16  = 21
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_UINT32  = 22
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_SIGNMAG8  = 23
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_SIGNMAG16  = 24
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_FLOAT_2_SIGNMAG32  = 25
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_SIGNMAG8_2_FLOAT  = 26
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_SIGNMAG16_2_FLOAT  = 27
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_SIGNMAG32_2_FLOAT  = 28
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_TYPE_COUNT_  = 29
# ConfigurationSerialStreamItem_modifiable_TS.data_format
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_DATA_BITS_SHIFT  = 0
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_DATA_BITS_MASK  = 0x00000003
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_DATA_BITS_BITS7  = 0x00000000
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_DATA_BITS_BITS8  = 0x00000001
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_DATA_BITS_COUNT_  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PARITY_SHIFT  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PARITY_MASK  = 0x0000000C
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PARITY_PARITY_NONE  = 0x00000000
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PARITY_PARITY_EVEN  = 0x00000004
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PARITY_PARITY_ODD  = 0x00000008
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PARITY_COUNT_  = 3
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_STOP_BITS_SHIFT  = 4
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_STOP_BITS_MASK  = 0x00000010
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_STOP_BITS_STOPBITS1  = 0x00000000
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_STOP_BITS_STOPBITS2  = 0x00000010
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_STOP_BITS_COUNT_  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PCLK_DIV_SHIFT  = 5
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PCLK_DIV_MASK  = 0x00000060
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PCLK_DIV_PCLK_DIV_1  = 0x00000000
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PCLK_DIV_PCLK_DIV_4  = 0x00000020
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PCLK_DIV_PCLK_DIV_16  = 0x00000040
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PCLK_DIV_PCLK_DIV_64  = 0x00000060
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_PCLK_DIV_COUNT_  = 4
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_BAUDRATEGEN_N_SHIFT  = 8
TS_SERIALSTREAM_ITEM_MODIFIABLE_DATA_FORMAT_BAUDRATEGEN_N_MASK  = 0x0000FF00
# ConfigurationSerialStreamItem_modifiable_TS.event_latch
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_SHIFT  = 0
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_MASK  = 0x03
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_RISING_EDGE  = 0x01
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_EDGE_FALLING_EDGE  = 0x02
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_SHIFT  = 4
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_MASK  = 0x30
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_ZERO  = 0x00
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_NON_ZERO  = 0x10
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_START_STATE_COUNT_  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED_SHIFT  = 6
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED_MASK  = 0x40
TS_SERIALSTREAM_ITEM_MODIFIABLE_EVENT_LATCH_INITIALIZED__  = 0x40
# ConfigurationSerialStreamItem_modifiable_TS.channel_bus_override
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_SHIFT  = 1
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_MASK  = 0x02
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_CHANNELA  = 0x00
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_CHANNELB  = 0x02
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_CHANNEL_COUNT_  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_SHIFT  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_MASK  = 0x04
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_TRANSMIT  = 0x00
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_RECEIVE  = 0x04
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_BUS_DIRECTION_COUNT_  = 2
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_SHIFT  = 3
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_MASK  = 0x08
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_PERIODIC  = 0x00
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_EVENT  = 0x08
TS_SERIALSTREAM_ITEM_MODIFIABLE_CHANNEL_BUS_OVERRIDE_MODE_TX_COUNT_  = 2
class ConfigurationSerialStreamItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS),
				("internal_inputs",  GenericArray_DTS),
				("internal_input_data_pointers",  GenericArray_DTS),
				("data_min_value",  GenericArray_DTS),
				("data_max_value",  GenericArray_DTS),
				("data_shift",  GenericArray_DTS),
				("data_bits",  GenericArray_DTS),
				("data_valid",  GenericArray_DTS),
				("data_type",  GenericArray_DTS),
				("data_format",  c_ulong),
				("data_buffer",  GenericArray_DTS),
				("stream_length",  c_ushort),
				("event_latch",  c_ubyte),
				("channel_bus_override",  c_ubyte)]

class ConfigurationEngineTimingGeneratorItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]

class ConfigurationHwPlaceHolderItem_modifiable_TS(Structure):
	_fields_ = [("header",  ConfigurationItemHeader_modifiable_TS)]


